<?xml version="1.0" encoding="utf-8"?><Database Name="FikrPos" Class="FikrPosDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=COREI3\sqlexpress;Initial Catalog=FikrPos;Integrated Security=True" SettingsObjectName="FikrPos.Properties.Settings" SettingsPropertyName="FikrPosConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.AppInfo" Member="AppInfos">
    <Type Name="AppInfo">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IsInit" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="[Company Name]" Member="Company_Name" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="[Company Address]" Member="Company_Address" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.AppUser" Member="AppUsers">
    <Type Name="AppUser">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Role" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="AppUser_Sale" Member="Sales" ThisKey="ID" OtherKey="UserId" Type="Sale" />
    </Type>
  </Table>
  <Table Name="dbo.SaleDetail" Member="SaleDetails">
    <Type Name="SaleDetail">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Qty" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Tax" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Discount" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="[Extended Price]" Member="Extended_Price" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="SaleID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="SaleDetail_Inventory" Member="Inventories" ThisKey="ID" OtherKey="SaleDetailID" Type="Inventory" />
      <Association Name="SaleDetail_InventoryDetail" Member="InventoryDetails" ThisKey="ID" OtherKey="SaleDetailID" Type="InventoryDetail" />
      <Association Name="Sale_SaleDetail" Member="Sale" ThisKey="SaleID" OtherKey="ID" Type="Sale" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Product_SaleDetail" Member="Product" ThisKey="ProductID" OtherKey="ID" Type="Product" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
    <InsertFunction FunctionId="FunctionId1">
      <Argument Parameter="saleDetailID" Member="ID" />
      <Argument Parameter="productID" Member="ProductID" />
      <Argument Parameter="qty" Member="Qty" />
      <Argument Parameter="tax" Member="Tax" />
      <Argument Parameter="discount" Member="Discount" />
      <Argument Parameter="price" Member="Price" />
      <Argument Parameter="saleID" Member="SaleID" />
    </InsertFunction>
  </Table>
  <Table Name="dbo.Sale" Member="Sales">
    <Type Name="Sale">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Total Quantity]" Member="Total_Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[Total Discount]" Member="Total_Discount" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[Total Tax]" Member="Total_Tax" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[Total Price]" Member="Total_Price" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="[Total Extended Price]" Member="Total_Extended_Price" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Payment" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Change" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="Sale_SaleDetail" Member="SaleDetails" ThisKey="ID" OtherKey="SaleID" Type="SaleDetail" />
      <Association Name="AppUser_Sale" Member="AppUser" ThisKey="UserId" OtherKey="ID" Type="AppUser" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Product" Member="Products">
    <Type Name="Product">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Unit" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Discount" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Tax" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="Product_SaleDetail" Member="SaleDetails" ThisKey="ID" OtherKey="ProductID" Type="SaleDetail" />
      <Association Name="Product_Inventory" Member="Inventories" ThisKey="ID" OtherKey="ProductID" Type="Inventory" />
    </Type>
  </Table>
  <Table Name="dbo.Inventory" Member="Inventories">
    <Type Name="Inventory">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Current Quantity]" Member="Current_Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="SaleDetailID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[Minimum Stock]" Member="Minimum_Stock" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Inventory_InventoryDetail" Member="InventoryDetails" ThisKey="ID" OtherKey="InventoryID" Type="InventoryDetail" />
      <Association Name="Product_Inventory" Member="Product" ThisKey="ProductID" OtherKey="ID" Type="Product" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="SaleDetail_Inventory" Member="SaleDetail" ThisKey="SaleDetailID" OtherKey="ID" Type="SaleDetail" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.InventoryDetail" Member="InventoryDetails">
    <Type Name="InventoryDetail">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="InventoryID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="SaleDetailID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Change" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Message" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="[Current Stock]" Member="Current_Stock" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Inventory_InventoryDetail" Member="Inventory" ThisKey="InventoryID" OtherKey="ID" Type="Inventory" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="SaleDetail_InventoryDetail" Member="SaleDetail" ThisKey="SaleDetailID" OtherKey="ID" Type="SaleDetail" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.InsertProduct" Method="InsertProduct">
    <Parameter Name="Code" Parameter="code" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="Price" Parameter="price" Type="System.Double" DbType="Float" />
    <Parameter Name="Unit" Parameter="unit" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="Discount" Parameter="discount" Type="System.Double" DbType="Float" />
    <Parameter Name="Tax" Parameter="tax" Type="System.Double" DbType="Float" />
    <Parameter Name="Stock" Parameter="stock" Type="System.Int32" DbType="Int" />
    <Parameter Name="MinimumStock" Parameter="minimumStock" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Id="FunctionId1" Name="dbo.InsertSaleDetail" Method="InsertSaleDetail">
    <Parameter Name="SaleDetailID" Parameter="saleDetailID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ProductID" Parameter="productID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Qty" Parameter="qty" Type="System.Int32" DbType="Int" />
    <Parameter Name="Tax" Parameter="tax" Type="System.Double" DbType="Float" />
    <Parameter Name="Discount" Parameter="discount" Type="System.Double" DbType="Float" />
    <Parameter Name="Price" Parameter="price" Type="System.Double" DbType="Float" />
    <Parameter Name="SaleID" Parameter="saleID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
</Database>